#!/bin/bash

####################################################################################################
#
#Description:
#
#Sysnopsis:
#
#Options：
#
#History:
#
#
#									Author:tim
#									 Email:lzcgame@126.com	
#									    QQ:20170748
####################################################################################################


function help(){
	cat <<HERE_DOCUMENT

HERE_DOCUMENT
return 0
}


