#!/bin/bash

####################################################################################################
#
#Description:
#
#Sysnopsis:
#
#Options：
#
#History:
#
#
#									Author:tim
#									 Email:lzcgame@126.com	
#									    QQ:20170748
####################################################################################################

#here document
function help(){
	cat <<HERE_DOCUMENT

HERE_DOCUMENT
return 0
}

#去掉指令名
shift
#解释指令参数
while [ -n "$1" ] ; do
	case $1 in
		-h|--help)
			help
			shift
			;;
		*)
			shift

		;;
	esac
done


exit 0
